"""CADENCE Layer 2: per-modality preprocessing.

Each submodule exposes:

    preprocess_<modality>_session(session_id, *,
                                  digest_dir, out_dir, force=False) -> dict

Contract
--------
* **Input:** session_id (string), the session's digest only.
* **Output:** writes ``<session_id>.npz`` (per-participant cleaned arrays + ts)
  and ``<session_id>.json`` (provenance, parameters, ``digest_xdf_md5`` for
  staleness — mismatch raises).
* **Idempotent:** if output exists and ``digest_xdf_md5`` matches, skip.
* **Per-participant only.** Cross-participant features (interbrain coherence,
  dyadic synchrony) belong in ``cadence/coupling/``, not here.

Submodules
----------
* ``cadence.preprocess.eeg``  — wraps MATLAB EEGLAB (ASR + 1–40 Hz FIR + interp).
* ``cadence.preprocess.face`` — 52-AU gap-fill, low-pass, z-score; optional V7 PCA.
* ``cadence.preprocess.ecg``  — bandpass, R-peaks, IBI, V8.2 6-ch HRV.
* ``cadence.preprocess.pose`` — 133->33 body-only gather, visibility-aware features.
* ``cadence.preprocess.respiratory`` — placeholder for future Polar H10 FMRR.
* ``cadence.preprocess.audio`` — placeholder.

CLI is generated by ``cadence.preprocess._cli.make_modality_cli(preprocess_fn)``;
each submodule's ``cli.py`` is a 3-line wrapper.
"""
